// Auto-generated by scripts/i18n/split-dictionaries.mjs
// Do not edit manually.
import type { Locale } from "../config";
import type { TranslationDictionary } from "../dictionaries/types";

export const chunkLoaders: Record<Locale, Record<string, () => Promise<{ default: TranslationDictionary }>>> = {
  "en": {
    "misc": () => import("./en/misc.json"),
    "admin/audit": () => import("./en/admin/audit.json"),
    "admin/featureSettings": () => import("./en/admin/featureSettings.json"),
    "admin/notifications": () => import("./en/admin/notifications.json"),
    "admin/roles": () => import("./en/admin/roles.json"),
    "admin/routeMetrics": () => import("./en/admin/routeMetrics.json"),
    "admin/users": () => import("./en/admin/users.json"),
    "api/error": () => import("./en/api/error.json"),
    "aqar/filters": () => import("./en/aqar/filters.json"),
    "ats/applications": () => import("./en/ats/applications.json"),
    "ats/interviews": () => import("./en/ats/interviews.json"),
    "ats/jobs": () => import("./en/ats/jobs.json"),
    "dashboard/hrRecruitment": () => import("./en/dashboard/hrRecruitment.json"),
    "finance/budget": () => import("./en/finance/budget.json"),
    "finance/expense": () => import("./en/finance/expense.json"),
    "finance/invoice": () => import("./en/finance/invoice.json"),
    "finance/payment": () => import("./en/finance/payment.json"),
    "fm/assets": () => import("./en/fm/assets.json"),
    "fm/compliance": () => import("./en/fm/compliance.json"),
    "fm/crm": () => import("./en/fm/crm.json"),
    "fm/finance": () => import("./en/fm/finance.json"),
    "fm/invoices": () => import("./en/fm/invoices.json"),
    "fm/projects": () => import("./en/fm/projects.json"),
    "fm/properties": () => import("./en/fm/properties.json"),
    "fm/rfqs": () => import("./en/fm/rfqs.json"),
    "fm/support": () => import("./en/fm/support.json"),
    "fm/tenants": () => import("./en/fm/tenants.json"),
    "fm/vendors": () => import("./en/fm/vendors.json"),
    "hr/ats": () => import("./en/hr/ats.json"),
    "hr/attendance": () => import("./en/hr/attendance.json"),
    "hr/leave": () => import("./en/hr/leave.json"),
    "hr/payroll": () => import("./en/hr/payroll.json"),
    "marketplace/sellerCentral": () => import("./en/marketplace/sellerCentral.json"),
    "marketplace/sellerOnboarding": () => import("./en/marketplace/sellerOnboarding.json"),
    "payments/tap": () => import("./en/payments/tap.json"),
    "properties/leases": () => import("./en/properties/leases.json"),
    "seller/advertising": () => import("./en/seller/advertising.json"),
    "seller/analytics": () => import("./en/seller/analytics.json"),
    "seller/health": () => import("./en/seller/health.json"),
    "sidebar/admin": () => import("./en/sidebar/admin.json"),
    "sidebar/legacy": () => import("./en/sidebar/legacy.json"),
    "support/subCategories": () => import("./en/support/subCategories.json"),
    "workOrders/history": () => import("./en/workOrders/history.json"),
    "workOrders/pm": () => import("./en/workOrders/pm.json")
  },
  "ar": {
    "misc": () => import("./ar/misc.json"),
    "admin/audit": () => import("./ar/admin/audit.json"),
    "admin/featureSettings": () => import("./ar/admin/featureSettings.json"),
    "admin/notifications": () => import("./ar/admin/notifications.json"),
    "admin/roles": () => import("./ar/admin/roles.json"),
    "admin/routeMetrics": () => import("./ar/admin/routeMetrics.json"),
    "admin/users": () => import("./ar/admin/users.json"),
    "api/error": () => import("./ar/api/error.json"),
    "aqar/filters": () => import("./ar/aqar/filters.json"),
    "ats/applications": () => import("./ar/ats/applications.json"),
    "ats/interviews": () => import("./ar/ats/interviews.json"),
    "ats/jobs": () => import("./ar/ats/jobs.json"),
    "dashboard/hrRecruitment": () => import("./ar/dashboard/hrRecruitment.json"),
    "finance/budget": () => import("./ar/finance/budget.json"),
    "finance/expense": () => import("./ar/finance/expense.json"),
    "finance/invoice": () => import("./ar/finance/invoice.json"),
    "finance/payment": () => import("./ar/finance/payment.json"),
    "fm/assets": () => import("./ar/fm/assets.json"),
    "fm/compliance": () => import("./ar/fm/compliance.json"),
    "fm/crm": () => import("./ar/fm/crm.json"),
    "fm/finance": () => import("./ar/fm/finance.json"),
    "fm/invoices": () => import("./ar/fm/invoices.json"),
    "fm/projects": () => import("./ar/fm/projects.json"),
    "fm/properties": () => import("./ar/fm/properties.json"),
    "fm/rfqs": () => import("./ar/fm/rfqs.json"),
    "fm/support": () => import("./ar/fm/support.json"),
    "fm/tenants": () => import("./ar/fm/tenants.json"),
    "fm/vendors": () => import("./ar/fm/vendors.json"),
    "hr/ats": () => import("./ar/hr/ats.json"),
    "hr/attendance": () => import("./ar/hr/attendance.json"),
    "hr/leave": () => import("./ar/hr/leave.json"),
    "hr/payroll": () => import("./ar/hr/payroll.json"),
    "marketplace/sellerCentral": () => import("./ar/marketplace/sellerCentral.json"),
    "marketplace/sellerOnboarding": () => import("./ar/marketplace/sellerOnboarding.json"),
    "payments/tap": () => import("./ar/payments/tap.json"),
    "properties/leases": () => import("./ar/properties/leases.json"),
    "seller/advertising": () => import("./ar/seller/advertising.json"),
    "seller/analytics": () => import("./ar/seller/analytics.json"),
    "seller/health": () => import("./ar/seller/health.json"),
    "sidebar/admin": () => import("./ar/sidebar/admin.json"),
    "sidebar/legacy": () => import("./ar/sidebar/legacy.json"),
    "support/subCategories": () => import("./ar/support/subCategories.json"),
    "workOrders/history": () => import("./ar/workOrders/history.json"),
    "workOrders/pm": () => import("./ar/workOrders/pm.json")
  }
} as const;

export const chunkManifest = {
  "en": [
    {
      "namespace": "misc",
      "path": "./en/misc.json"
    },
    {
      "namespace": "admin/audit",
      "path": "./en/admin/audit.json"
    },
    {
      "namespace": "admin/featureSettings",
      "path": "./en/admin/featureSettings.json"
    },
    {
      "namespace": "admin/notifications",
      "path": "./en/admin/notifications.json"
    },
    {
      "namespace": "admin/roles",
      "path": "./en/admin/roles.json"
    },
    {
      "namespace": "admin/routeMetrics",
      "path": "./en/admin/routeMetrics.json"
    },
    {
      "namespace": "admin/users",
      "path": "./en/admin/users.json"
    },
    {
      "namespace": "api/error",
      "path": "./en/api/error.json"
    },
    {
      "namespace": "aqar/filters",
      "path": "./en/aqar/filters.json"
    },
    {
      "namespace": "ats/applications",
      "path": "./en/ats/applications.json"
    },
    {
      "namespace": "ats/interviews",
      "path": "./en/ats/interviews.json"
    },
    {
      "namespace": "ats/jobs",
      "path": "./en/ats/jobs.json"
    },
    {
      "namespace": "dashboard/hrRecruitment",
      "path": "./en/dashboard/hrRecruitment.json"
    },
    {
      "namespace": "finance/budget",
      "path": "./en/finance/budget.json"
    },
    {
      "namespace": "finance/expense",
      "path": "./en/finance/expense.json"
    },
    {
      "namespace": "finance/invoice",
      "path": "./en/finance/invoice.json"
    },
    {
      "namespace": "finance/payment",
      "path": "./en/finance/payment.json"
    },
    {
      "namespace": "fm/assets",
      "path": "./en/fm/assets.json"
    },
    {
      "namespace": "fm/compliance",
      "path": "./en/fm/compliance.json"
    },
    {
      "namespace": "fm/crm",
      "path": "./en/fm/crm.json"
    },
    {
      "namespace": "fm/finance",
      "path": "./en/fm/finance.json"
    },
    {
      "namespace": "fm/invoices",
      "path": "./en/fm/invoices.json"
    },
    {
      "namespace": "fm/projects",
      "path": "./en/fm/projects.json"
    },
    {
      "namespace": "fm/properties",
      "path": "./en/fm/properties.json"
    },
    {
      "namespace": "fm/rfqs",
      "path": "./en/fm/rfqs.json"
    },
    {
      "namespace": "fm/support",
      "path": "./en/fm/support.json"
    },
    {
      "namespace": "fm/tenants",
      "path": "./en/fm/tenants.json"
    },
    {
      "namespace": "fm/vendors",
      "path": "./en/fm/vendors.json"
    },
    {
      "namespace": "hr/ats",
      "path": "./en/hr/ats.json"
    },
    {
      "namespace": "hr/attendance",
      "path": "./en/hr/attendance.json"
    },
    {
      "namespace": "hr/leave",
      "path": "./en/hr/leave.json"
    },
    {
      "namespace": "hr/payroll",
      "path": "./en/hr/payroll.json"
    },
    {
      "namespace": "marketplace/sellerCentral",
      "path": "./en/marketplace/sellerCentral.json"
    },
    {
      "namespace": "marketplace/sellerOnboarding",
      "path": "./en/marketplace/sellerOnboarding.json"
    },
    {
      "namespace": "payments/tap",
      "path": "./en/payments/tap.json"
    },
    {
      "namespace": "properties/leases",
      "path": "./en/properties/leases.json"
    },
    {
      "namespace": "seller/advertising",
      "path": "./en/seller/advertising.json"
    },
    {
      "namespace": "seller/analytics",
      "path": "./en/seller/analytics.json"
    },
    {
      "namespace": "seller/health",
      "path": "./en/seller/health.json"
    },
    {
      "namespace": "sidebar/admin",
      "path": "./en/sidebar/admin.json"
    },
    {
      "namespace": "sidebar/legacy",
      "path": "./en/sidebar/legacy.json"
    },
    {
      "namespace": "support/subCategories",
      "path": "./en/support/subCategories.json"
    },
    {
      "namespace": "workOrders/history",
      "path": "./en/workOrders/history.json"
    },
    {
      "namespace": "workOrders/pm",
      "path": "./en/workOrders/pm.json"
    }
  ],
  "ar": [
    {
      "namespace": "misc",
      "path": "./ar/misc.json"
    },
    {
      "namespace": "admin/audit",
      "path": "./ar/admin/audit.json"
    },
    {
      "namespace": "admin/featureSettings",
      "path": "./ar/admin/featureSettings.json"
    },
    {
      "namespace": "admin/notifications",
      "path": "./ar/admin/notifications.json"
    },
    {
      "namespace": "admin/roles",
      "path": "./ar/admin/roles.json"
    },
    {
      "namespace": "admin/routeMetrics",
      "path": "./ar/admin/routeMetrics.json"
    },
    {
      "namespace": "admin/users",
      "path": "./ar/admin/users.json"
    },
    {
      "namespace": "api/error",
      "path": "./ar/api/error.json"
    },
    {
      "namespace": "aqar/filters",
      "path": "./ar/aqar/filters.json"
    },
    {
      "namespace": "ats/applications",
      "path": "./ar/ats/applications.json"
    },
    {
      "namespace": "ats/interviews",
      "path": "./ar/ats/interviews.json"
    },
    {
      "namespace": "ats/jobs",
      "path": "./ar/ats/jobs.json"
    },
    {
      "namespace": "dashboard/hrRecruitment",
      "path": "./ar/dashboard/hrRecruitment.json"
    },
    {
      "namespace": "finance/budget",
      "path": "./ar/finance/budget.json"
    },
    {
      "namespace": "finance/expense",
      "path": "./ar/finance/expense.json"
    },
    {
      "namespace": "finance/invoice",
      "path": "./ar/finance/invoice.json"
    },
    {
      "namespace": "finance/payment",
      "path": "./ar/finance/payment.json"
    },
    {
      "namespace": "fm/assets",
      "path": "./ar/fm/assets.json"
    },
    {
      "namespace": "fm/compliance",
      "path": "./ar/fm/compliance.json"
    },
    {
      "namespace": "fm/crm",
      "path": "./ar/fm/crm.json"
    },
    {
      "namespace": "fm/finance",
      "path": "./ar/fm/finance.json"
    },
    {
      "namespace": "fm/invoices",
      "path": "./ar/fm/invoices.json"
    },
    {
      "namespace": "fm/projects",
      "path": "./ar/fm/projects.json"
    },
    {
      "namespace": "fm/properties",
      "path": "./ar/fm/properties.json"
    },
    {
      "namespace": "fm/rfqs",
      "path": "./ar/fm/rfqs.json"
    },
    {
      "namespace": "fm/support",
      "path": "./ar/fm/support.json"
    },
    {
      "namespace": "fm/tenants",
      "path": "./ar/fm/tenants.json"
    },
    {
      "namespace": "fm/vendors",
      "path": "./ar/fm/vendors.json"
    },
    {
      "namespace": "hr/ats",
      "path": "./ar/hr/ats.json"
    },
    {
      "namespace": "hr/attendance",
      "path": "./ar/hr/attendance.json"
    },
    {
      "namespace": "hr/leave",
      "path": "./ar/hr/leave.json"
    },
    {
      "namespace": "hr/payroll",
      "path": "./ar/hr/payroll.json"
    },
    {
      "namespace": "marketplace/sellerCentral",
      "path": "./ar/marketplace/sellerCentral.json"
    },
    {
      "namespace": "marketplace/sellerOnboarding",
      "path": "./ar/marketplace/sellerOnboarding.json"
    },
    {
      "namespace": "payments/tap",
      "path": "./ar/payments/tap.json"
    },
    {
      "namespace": "properties/leases",
      "path": "./ar/properties/leases.json"
    },
    {
      "namespace": "seller/advertising",
      "path": "./ar/seller/advertising.json"
    },
    {
      "namespace": "seller/analytics",
      "path": "./ar/seller/analytics.json"
    },
    {
      "namespace": "seller/health",
      "path": "./ar/seller/health.json"
    },
    {
      "namespace": "sidebar/admin",
      "path": "./ar/sidebar/admin.json"
    },
    {
      "namespace": "sidebar/legacy",
      "path": "./ar/sidebar/legacy.json"
    },
    {
      "namespace": "support/subCategories",
      "path": "./ar/support/subCategories.json"
    },
    {
      "namespace": "workOrders/history",
      "path": "./ar/workOrders/history.json"
    },
    {
      "namespace": "workOrders/pm",
      "path": "./ar/workOrders/pm.json"
    }
  ]
} as const;
