# CodeRabbit Configuration for Fixzit
# AI-powered code review integration
# Created by [AGENT-0039]

version: "2"

# Review settings
reviews:
  # Enable auto-review on PRs
  auto_review:
    enabled: true
    # Review drafts as well
    drafts: false
    # Base branch to compare against
    base_branch: "main"

  # Review profile - thorough for production code
  profile: "assertive"

  # Request changes on high severity issues
  request_changes_workflow: true

  # High-level summary at the end of review
  high_level_summary: true

  # Generate poem/fun summary (disabled for professional reviews)
  poem: false

  # Review hints
  review_status: true

  # Path-based instructions
  path_instructions:
    # API routes - focus on security and multi-tenancy
    - path: "app/api/**"
      instructions: |
        - Verify all database queries include org_id or tenant scoping
        - Check for proper authentication via requireAuth/getSessionOrThrow
        - Ensure rate limiting is applied where needed
        - Validate input with Zod schemas
        - Check for proper error handling (no silent catches)

    # Components - focus on UI/UX and accessibility
    - path: "components/**"
      instructions: |
        - Verify RTL support using logical CSS properties (ps-*, pe-*, ms-*, me-*)
        - Check for proper use of design system tokens
        - Ensure accessibility (aria-labels, keyboard navigation)
        - Verify 'use client' directive for hooks

    # Models - focus on schema integrity
    - path: "models/**"
      instructions: |
        - Verify org_id field is required for multi-tenant collections
        - Check for proper indexes on frequently queried fields
        - Ensure timestamps (createdAt, updatedAt) are present
        - Validate enum values match domain requirements

    # Services - focus on business logic
    - path: "services/**"
      instructions: |
        - Verify proper error handling and logging
        - Check for tenant isolation in all operations
        - Ensure transactions are used for multi-document operations
        - Validate business rules match domain requirements

    # Finance domain - extra compliance scrutiny
    - path: "domain/finance/**"
      instructions: |
        - Verify ZATCA compliance for Saudi e-invoicing
        - Check VAT calculations (15% standard rate)
        - Ensure audit trail for all financial operations
        - Validate currency handling (SAR default)

    # Tests - ensure coverage
    - path: "tests/**"
      instructions: |
        - Verify test isolation (no shared state)
        - Check for proper mocking of external services
        - Ensure both success and error paths are tested
        - Validate tenant scoping in test fixtures

# Language settings
language: "en-US"

# Chat settings
chat:
  # Allow interactive review
  auto_reply: true

# Tool integrations
tools:
  # Enable ESLint integration
  eslint:
    enabled: true

  # Enable TypeScript checks
  typescript:
    enabled: true

# Ignore patterns
path_filters:
  # Exclude generated files
  - "!**/*.gen.ts"
  - "!**/generated/**"
  - "!.next/**"
  - "!node_modules/**"
  - "!pnpm-lock.yaml"
  - "!**/dist/**"
  - "!**/build/**"
  - "!playwright-report/**"
  - "!coverage/**"

  # Exclude documentation (manual review)
  - "!docs/**/*.md"

  # Exclude config files (low risk)
  - "!*.config.js"
  - "!*.config.ts"
  - "!*.config.mjs"

# Early access features
early_access: false

# Knowledge base
knowledge_base:
  # Reference key documents
  learnings:
    scope: "auto"

  # Custom instructions from repository
  jira:
    enabled: false

  # GitHub issues integration
  issues:
    enabled: true
