# CodeRabbit AI Code Review Configuration
# DEV-003: AI-powered code review for Fixzit
# @author [AGENT-0041]
# @created 2026-01-07

version: 2

reviews:
  # Enable automatic reviews on PRs
  auto_review:
    enabled: true
    drafts: false  # Don't review draft PRs
    base_branches:
      - main
      - develop

  # Review settings
  request_changes_workflow: false
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_instructions: []

  # Language-specific settings
  language: en

# Domain-specific review instructions
instructions:
  # Multi-tenancy enforcement
  - pattern: "**/*.ts"
    instructions: |
      - Verify all database queries include org_id/orgId scoping
      - Check for cross-tenant data leakage risks
      - Ensure RBAC is enforced server-side, not just UI

  # API routes security
  - pattern: "app/api/**/*.ts"
    instructions: |
      - Verify authentication is checked (getServerSession)
      - Check rate limiting is applied
      - Ensure proper error handling (no sensitive data in responses)
      - Verify input validation with Zod or similar

  # Finance/ZATCA compliance
  - pattern: "**/*finance*/**/*.ts"
    instructions: |
      - Check ZATCA e-invoicing compliance requirements
      - Verify VAT calculations are accurate
      - Ensure audit trail for all financial operations

  - pattern: "**/*zatca*/**/*.ts"
    instructions: |
      - Verify Phase 2 compliance (signing, clearance, reporting)
      - Check certificate handling security
      - Ensure proper error handling for ZATCA API calls

  # RTL/i18n requirements
  - pattern: "**/*.tsx"
    instructions: |
      - Check for RTL-safe CSS (use ps-/pe-/ms-/me- instead of pl-/pr-/ml-/mr-)
      - Verify text direction handling for Arabic content
      - Ensure all user-facing strings use i18n keys

  # Security-sensitive files
  - pattern: "**/auth/**/*.ts"
    instructions: |
      - Check for timing-safe comparisons in credential checks
      - Verify session handling security
      - Ensure MFA flows are properly implemented

  - pattern: "**/lib/security/**/*.ts"
    instructions: |
      - Verify encryption/decryption implementations
      - Check for secure random number generation
      - Ensure no hardcoded secrets or keys

  # Test files
  - pattern: "tests/**/*.ts"
    instructions: |
      - Verify tests cover multi-tenant isolation
      - Check for proper mocking of external services
      - Ensure edge cases are covered

# Files to ignore
ignore:
  - "*.md"
  - "*.json"
  - "*.yaml"
  - "*.yml"
  - ".next/**"
  - "node_modules/**"
  - "dist/**"
  - "build/**"
  - "coverage/**"
  - "*.d.ts"
  - "i18n/generated/**"
  - "i18n/chunks/**"

# Chat settings
chat:
  auto_reply: true
