import fs from "node:fs";

const candidates = [
  "openapi.yaml",
  "openapi.yml",
  "apps/api/openapi.yaml",
  "apps/api/openapi.yml",
];

const existing = candidates.find((p) => fs.existsSync(p));
if (existing) {
  console.log(`[openapi] found ${existing}, copying to ./openapi.yaml`);
  if (existing !== "openapi.yaml") {
    fs.copyFileSync(existing, "openapi.yaml");
  }
  process.exit(0);
}

// Opinionated skeleton so CI has a useful artifact to review
const skeleton = `openapi: 3.0.3
info:
  title: Fixzit API
  version: 0.1.0
  description: |
    Provisional specification generated by scripts/openapi/build.mjs when a
    project-specific OpenAPI document cannot be located. Replace this file with
    the authoritative Fixzit API definition to capture every route and schema.
servers:
  - url: https://api.fixzit.com/v1
    description: Production
  - url: https://staging-api.fixzit.com/v1
    description: Staging
  - url: http://localhost:3000/api
    description: Local development
paths:
  /health:
    get:
      summary: Service health probe
      tags: [System]
      responses:
        '200':
          description: API is reachable
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  version:
                    type: string
                    example: 2.0.26
  /api/work-orders:
    get:
      summary: List work orders for a tenant
      tags: [Facilities]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: orgId
          required: true
          schema:
            type: string
        - in: query
          name: status
          schema:
            type: string
            enum: [open, in_progress, closed]
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
      responses:
        '200':
          description: Paginated list of work orders
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkOrderList'
  /api/marketplace/products:
    get:
      summary: Search marketplace catalogue
      tags: [Marketplace]
      security:
        - bearerAuth: []
      parameters:
        - in: query
          name: q
          schema:
            type: string
        - in: query
          name: category
          schema:
            type: string
        - in: query
          name: limit
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 20
      responses:
        '200':
          description: Matching products
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductList'
security:
  - bearerAuth: []
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    WorkOrder:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        status:
          type: string
          enum: [open, in_progress, closed]
        priority:
          type: string
          enum: [low, medium, high, urgent]
        orgId:
          type: string
        assigneeId:
          type: string
        createdAt:
          type: string
          format: date-time
    WorkOrderList:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/WorkOrder'
        meta:
          type: object
          properties:
            total:
              type: integer
            limit:
              type: integer
            offset:
              type: integer
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        currency:
          type: string
          example: SAR
        vendorId:
          type: string
    ProductList:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        meta:
          type: object
          properties:
            total:
              type: integer
            limit:
              type: integer
            offset:
              type: integer
    ErrorResponse:
      type: object
      required: [code, userMessage]
      properties:
        code:
          type: string
          example: TENANT_NOT_AUTHORISED
        userMessage:
          type: string
          example: "You do not have access to this tenant."
        devMessage:
          type: string
        correlationId:
          type: string
          format: uuid
`;
fs.writeFileSync("openapi.yaml", skeleton);
console.log("[openapi] skeleton created at ./openapi.yaml");
