#!/bin/bash
# Archive Strategy - Archive completion reports after each major milestone
# Run: ./scripts/archive-milestone.sh "Milestone Name"

set -e

MILESTONE_NAME="${1:-$(date '+%Y-%m-%d')}"
ARCHIVE_BASE="docs/archived/milestones"
TIMESTAMP=$(date '+%Y-%m-%d')

echo "=== Milestone Archive Strategy ==="
echo "Milestone: $MILESTONE_NAME"
echo "Date: $TIMESTAMP"
echo ""

# Create milestone directory
MILESTONE_DIR="$ARCHIVE_BASE/${TIMESTAMP}_${MILESTONE_NAME// /_}"
mkdir -p "$MILESTONE_DIR"

echo "Created archive directory: $MILESTONE_DIR"
echo ""

# List of patterns to archive from root
COMPLETION_PATTERNS=(
  "*COMPLETE*.md"
  "*COMPLETION*.md"
  "*REPORT*.md"
  "*SUMMARY*.md"
  "*FINDINGS*.md"
  "MISSION*.md"
)

echo "=== Searching for completion reports to archive ==="
echo ""

files_archived=0
total_size=0

for pattern in "${COMPLETION_PATTERNS[@]}"; do
  # Find matching files in root
  for file in $pattern 2>/dev/null; do
    if [ -f "$file" ]; then
      size=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file")
      size_mb=$(echo "scale=2; $size / 1024 / 1024" | bc)
      
      echo "Found: $file ($size_mb MB)"
      
      # Ask for confirmation (can be automated with -y flag)
      if [ "$2" != "-y" ]; then
        read -p "  Archive this file? (y/n) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
          echo "  Skipped"
          continue
        fi
      fi
      
      # Move to milestone archive
      mv -v "$file" "$MILESTONE_DIR/"
      files_archived=$((files_archived + 1))
      total_size=$((total_size + size))
      echo "  ✓ Archived"
      echo ""
    fi
  done
done

# Also check docs/current for completed items
if [ -d "docs/current" ]; then
  echo "=== Checking docs/current/ for completed items ==="
  echo ""
  
  find "docs/current" -type f -name "*.md" | while read -r file; do
    # Check if file contains "COMPLETE" or "DONE" markers
    if grep -qi "COMPLETE\|✅.*complete\|status.*complete" "$file" 2>/dev/null; then
      filename=$(basename "$file")
      size=$(stat -f%z "$file" 2>/dev/null || stat -c%s "$file")
      size_mb=$(echo "scale=2; $size / 1024 / 1024" | bc)
      
      echo "Found completed item: $filename ($size_mb MB)"
      
      if [ "$2" != "-y" ]; then
        read -p "  Archive this file? (y/n) " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
          echo "  Skipped"
          continue
        fi
      fi
      
      mv -v "$file" "$MILESTONE_DIR/"
      echo "  ✓ Archived"
      echo ""
    fi
  done
fi

# Create milestone summary
SUMMARY_FILE="$MILESTONE_DIR/MILESTONE_SUMMARY.md"
cat > "$SUMMARY_FILE" << EOF
# Milestone: $MILESTONE_NAME

**Date:** $TIMESTAMP  
**Archived by:** $(git config user.name 2>/dev/null || echo "System")

## Summary

This milestone archive was created on $TIMESTAMP.

### Files Archived
- Total files: $files_archived
- Total size: $(echo "scale=2; $total_size / 1024 / 1024" | bc) MB

### Files in Archive
$(ls -1 "$MILESTONE_DIR" | grep -v "MILESTONE_SUMMARY.md" | sed 's/^/- /')

### Git Commit
\`\`\`
$(git log -1 --oneline 2>/dev/null || echo "No git commit available")
\`\`\`

## Next Steps

1. Review archived files for completeness
2. Update project documentation with milestone achievements
3. Create new tracking documents for next phase
4. Commit changes to version control

---
*Generated by: scripts/archive-milestone.sh*
EOF

echo "=== Archive Complete ==="
echo ""
echo "Milestone: $MILESTONE_NAME"
echo "Location: $MILESTONE_DIR"
echo "Files archived: $files_archived"
echo "Summary created: $SUMMARY_FILE"
echo ""

if [ "$files_archived" -gt 0 ]; then
  echo "📋 Next steps:"
  echo "  1. Review: cat $SUMMARY_FILE"
  echo "  2. Commit: git add docs/archived/milestones && git commit -m 'chore: archive $MILESTONE_NAME milestone'"
  echo "  3. Push: git push origin main"
else
  echo "ℹ️  No files were archived for this milestone"
fi

echo ""
echo "✓ Milestone archive strategy executed"
